### PR TITLE
CXX: Improve function signature matching

### LINKED ISSUE #2181: C++ parser trips over template specialization
The name of the parser: c++

The command line you used to run ctags:

```
$ ctags --options=NONE --language-force=c++  --c++-types=nvdtcgsufp test.cpp
```

The content of input file:

```CPP
template <>
double ParseString<double>(const std::string &str, const std::string &errorMsg)
{
  throw IgorException(ERR_CONVERT, errorMsg);
}
```

The tags output you are not satisfied with:

```
!_TAG_FILE_FORMAT       2       /extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED       1       /0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_MODE       u-ctags /u-ctags or e-ctags/
!_TAG_PROGRAM_AUTHOR    Universal Ctags Team    //
!_TAG_PROGRAM_NAME      Universal Ctags /Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL       https://ctags.io/       /official site/
!_TAG_PROGRAM_VERSION   0.0.0   /1a94658c/
IgorException   test.cpp        /^  throw IgorException(ERR_CONVERT, errorMsg);$/;"     p       typeref:typename:throw      file:
```

The tags output you expect:

```
!_TAG_FILE_FORMAT       2       /extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED       1       /0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_MODE       u-ctags /u-ctags or e-ctags/
!_TAG_PROGRAM_AUTHOR    Universal Ctags Team    //
!_TAG_PROGRAM_NAME      Universal Ctags /Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL       https://ctags.io/       /official site/
!_TAG_PROGRAM_VERSION   0.0.0   /1a94658c/
ParseString<double>     test.cpp        /^double ParseString<double>(const std::string &str, const std::string &errorMsg)$/;"   f  typeref:typename:double
```

The version of ctags:

```
Universal Ctags 0.0.0(1a94658c), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jul 25 2019, 00:08:52
  URL: https://ctags.io/
  Optional compiled features: +win32, +wildcards, +regex, +internal-sort, +iconv, +option-directory, +xpath, +json, +interactive, +yaml, +case-insensitive-filenames, +packcc
```

How do you get ctags binary:

win32 binary taken from Universal-ctags/ctags-win32 project

### PR DESCRIPTION
**Pull request by pragmaware**
Improve matching of template specializations.
Avoid matching throw statements even if state is wrong.

Fixes #2181

### CODE REVIEW

File: parsers/cxx/cxx_parser_block.c [hunk 1]
```diff
@@ -485,13 +485,19 @@ static bool cxxParserParseBlockInternal(bool bExpectClosingBracket)
...
-						if(cxxScopeGetType() == CXXScopeTypeFunction)
+						// We ignore whole "throw expressions" as they contain nothing useful
+						// and may confuse us. We keep "throw" when used as exception specification,
+						// and this is certainly outside of a function and when the token chain
+						// already contains at least a type, an identifier and a parenthesis.
+						// This check seems excessive but keep in mind that we deal with
+						// broken input and we might also be wrong about the current scope.
+						if((cxxScopeGetType() == CXXScopeTypeFunction) || (g_cxx.pTokenChain->iCount < 3))
 						{
+							CXX_DEBUG_LEAVE_TEXT("Skipping throw statement");
```
Comment (masatake) [inline parsers/cxx/cxx_parser_block.c]: I thinks CXX_DEBUG_PRINT is suitable than CXX_DEBUG_LEAVE_TEXT because the controls is not returned caller here.

Comment (pragmaware) [reply parsers/cxx/cxx_parser_block.c]: Right. Good catch!

**Comment by pragmaware** [comment]
Can I merge this?

**Comment by masatake** [comment]
I'm sorry to be late. I cannot find enough time for reviewing the rest.
So, please merge this.
