### PR TITLE
main: truncate output file when rescan is failed

### LINKED ISSUE #2948: Invalid JSON In Interactive Mode
I noticed a parse failure in a program that uses universal ctag's interactive mode.  I managed to come up with the following reproduction case using [this file](https://github.com/llvm/llvm-project/blob/main/flang/test/Preprocessing/pp038.F) from the llvm-project repository:

When I run `universal-ctags` as follows, the output is valid:
```
$ universal-ctags --output-format=json pp038.F
{"_type": "tag", "name": "main", "path": "pp038.F", "pattern": "/^      program main$/", "kind": "program"}
{"_type": "tag", "name": "res", "path": "pp038.F", "pattern": "/^      integer :: res$/", "kind": "variable", "scope": "main", "scopeKind": "program"}
```

But using interactive mode, I get a third line that is not valid JSON output:
```
$ universal-ctags --_interactive
{"_type": "program", "name": "Universal Ctags", "version": "5.9.0"}
{"command":"generate-tags","filename":"pp038.F","size":440}
! RUN: %flang -E %s 2>&1 | FileCheck %s
! CHECK: res=((666)+111)
* FLM call with closing ')' on next line (not a continuation)
      integer function IFLM(x)
        integer :: x
        IFLM = x
      end function IFLM
      program main
#define IFLM(x) ((x)+111)
      integer :: res
      res = IFLM(666
)
      if (res .eq. 777) then
        print *, 'pp038.F yes'
      else
        print *, 'pp038.F no: ', res
      end if
      end
{"_type": "tag", "name": "main", "path": "pp038.F", "pattern": "/^      program main$/", "kind": "program"}
{"_type": "tag", "name": "res", "path": "pp038.F", "pattern": "/^      integer :: res$/", "kind": "variable", "scope": "main", "scopeKind": "program"}
path": "pp038.F", "pattern": "/^      integer :: res$/", "kind": "variable", "scope": "main", "scopeKind": "program"}
{"_type": "completed", "command": "generate-tags"}
^C
```

This is a copy of Ctags built from master just prior to creating this issue.

```
$ universal-ctags --version
Universal Ctags 5.9.0(6f06e29c), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Apr  8 2021, 20:17:01
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +json, +interactive, +sandbox, +packcc
```

### PR DESCRIPTION
**Pull request by masatake**
Close #2948.

When a parser returned RESCAN_FAILED, the original code
just moved the file position.

#2948 indicated reports just moving the file position put
noise to the otuput file; file truncation is needed after
moving the position.

Signed-off-by: Masatake YAMATO <yamato@redhat.com>

### CODE REVIEW

File: main/mio.c [hunk 1]
```diff
@@ -43,6 +43,13 @@
 #include <stdlib.h>
 #include <limits.h>
 
+#ifndef WIN32
+#ifndef _MSC_VER
```
Comment (k-takata) [inline main/mio.c:47]: Isn't this line redundant?
If `WIN32` isn't defined, `_MSC_VER` won't be defined.

Comment (masatake) [reply main/mio.c:47]: Oh, I see. Thank you!

**Comment by masatake** [comment]
The test running on cygwin says:
```
Can't locate threads.pm in @INC (you may need to install the threads module) (@INC contains: /usr/share/automake-1.16 /usr/local/lib/perl5/site_perl/5.32/x86_64-cygwin-threads /usr/local/share/perl5/site_perl/5.32 /usr/lib/perl5/vendor_perl/5.32/x86_64-cygwin-threads /usr/share/perl5/vendor_perl/5.32 /usr/lib/perl5/5.32/x86_64-cygwin-threads /usr/share/perl5/5.32) at /usr/share/automake-1.16/Automake/ChannelDefs.pm line 23.
```

Packaging bug?
threads.pm may be available at https://metacpan.org/pod/threads.

This may be the side effect of the version up of perl_base:

```
   2 install perl_base              5.32.1-1 
   3   erase perl_base              5.26.3-2 
```
The initial step for solving the issue may be:
```
for version between 5.26..5.32; do
 if !has_module(perl, $version, 'threads.pm'); then
    inspect_document(perl, $version)
    break
  fi
done
```

**Comment by masatake** [comment]
In my pc, thread.pm is installed at /usr/lib/perl5/5.32/x86_64-cygwin-threads/threads.pm.
On the other hand, the error message on Appveyor includes:
```
Can't locate threads.pm in @INC (...  /usr/lib/perl5/5.32/x86_64-cygwin-threads ...) at /usr/share/automake-1.16/Automake/ChannelDefs.pm line 23.
```

It looks strange.

**Comment by masatake** [comment]
What I got on Appveyor:
```
### begin: threads.pm debugging
+ ls -l /usr/lib/perl5/5.32/x86_64-cygwin-threads
total 268
-rw-r--r--  1 appveyor None 16353 Feb  6 11:46 attributes.pm
drwxr-xr-x+ 1 appveyor None     0 Apr 15 16:57 auto
-rw-r--r--  1 appveyor None 29474 Feb  6 11:46 B.pm
-rw-r--r--  1 appveyor None  3165 Feb  6 11:46 Config.pm
-rw-r--r--  1 appveyor None 43616 Feb  6 11:46 Config_heavy.pl
-rw-r--r--  1 appveyor None 21942 Feb  6 11:46 Cwd.pm
drwxr-xr-x+ 1 appveyor None     0 Apr 15 16:57 Data
drwxr-xr-x+ 1 appveyor None     0 Apr 15 16:57 Digest
-rw-r--r--  1 appveyor None 25310 Feb  6 11:46 DynaLoader.pm
drwxr-xr-x+ 1 appveyor None     0 Apr 15 16:57 Encode
-rw-r--r--  1 appveyor None 32083 Feb  6 11:46 Encode.pm
-rw-r--r--  1 appveyor None  6717 Feb  6 11:46 Errno.pm
-rw-r--r--  1 appveyor None  4044 Feb  6 11:46 Fcntl.pm
drwxr-xr-x+ 1 appveyor None     0 Apr 15 16:57 File
drwxr-xr-x+ 1 appveyor None     0 Apr 15 16:57 I18N
drwxr-xr-x+ 1 appveyor None     0 Apr 15 16:57 IO
-rw-r--r--  1 appveyor None  1456 Feb  6 11:46 IO.pm
-rw-r--r--  1 appveyor None  6136 Feb  6 11:46 lib.pm
drwxr-xr-x+ 1 appveyor None     0 Apr 15 16:57 List
drwxr-xr-x+ 1 appveyor None     0 Apr 15 16:57 MIME
-rw-r--r--  1 appveyor None  9892 Feb  6 11:46 mro.pm
-rw-r--r--  1 appveyor None 16226 Feb  6 11:46 Opcode.pm
drwxr-xr-x+ 1 appveyor None     0 Apr 15 16:57 PerlIO
-rw-r--r--  1 appveyor None 20347 Feb  6 11:46 POSIX.pm
-rw-r--r--  1 appveyor None 25394 Feb  6 11:46 re.pm
drwxr-xr-x+ 1 appveyor None     0 Apr 15 16:57 Scalar
-rw-r--r--  1 appveyor None 37062 Feb  6 11:46 Socket.pm
-rw-r--r--  1 appveyor None 49924 Feb  6 11:46 Storable.pm
drwxr-xr-x+ 1 appveyor None     0 Apr 15 16:57 Time
-rw-r--r--  1 appveyor None 52505 Feb  6 11:46 Win32.pm
drwxr-xr-x+ 1 appveyor None     0 Apr 15 16:57 Win32API
+ echo '### end: threads.pm debugging'
### end: threads.pm debugging
+ type autoreconf
+ type pkg-config
```
What I got on cygwin running on my VM.

```
total 949
drwxr-xr-x+ 1 jet なし      0 Apr 16 01:30 B
-rw-r--r--  1 jet なし  29474 Feb  6 20:46 B.pm
drwxr-xr-x+ 1 jet なし      0 Apr 16 01:30 CORE
drwxr-xr-x+ 1 jet なし      0 Apr 16 01:30 Compress
-rw-r--r--  1 jet なし   3165 Feb  6 20:46 Config.pm
-rw-r--r--  1 jet なし 254697 Feb  6 20:46 Config.pod
-rw-r--r--  1 jet なし    409 Feb  6 20:46 Config_git.pl
-rw-r--r--  1 jet なし  43616 Feb  6 20:46 Config_heavy.pl
-rw-r--r--  1 jet なし  21942 Feb  6 20:46 Cwd.pm
-rw-r--r--  1 jet なし  67111 Feb  6 20:46 DB_File.pm
drwxr-xr-x+ 1 jet なし      0 Apr 16 01:30 Data
drwxr-xr-x+ 1 jet なし      0 Apr 16 01:30 Devel
drwxr-xr-x+ 1 jet なし      0 Apr 16 01:30 Digest
-rw-r--r--  1 jet なし  25310 Feb  6 20:46 DynaLoader.pm
drwxr-xr-x+ 1 jet なし      0 Apr 16 01:30 Encode
-rw-r--r--  1 jet なし  32083 Feb  6 20:46 Encode.pm
-rw-r--r--  1 jet なし   6717 Feb  6 20:46 Errno.pm
-rw-r--r--  1 jet なし   4044 Feb  6 20:46 Fcntl.pm
drwxr-xr-x+ 1 jet なし      0 Apr 16 01:30 File
drwxr-xr-x+ 1 jet なし      0 Apr 16 01:30 Filter
-rw-r--r--  1 jet なし   2074 Feb  6 20:46 GDBM_File.pm
drwxr-xr-x+ 1 jet なし      0 Apr 16 01:30 Hash
drwxr-xr-x+ 1 jet なし      0 Apr 16 01:30 I18N
drwxr-xr-x+ 1 jet なし      0 Apr 16 01:30 IO
-rw-r--r--  1 jet なし   1456 Feb  6 20:46 IO.pm
drwxr-xr-x+ 1 jet なし      0 Apr 16 01:30 IPC
drwxr-xr-x+ 1 jet なし      0 Apr 16 01:30 List
drwxr-xr-x+ 1 jet なし      0 Apr 16 01:30 MIME
drwxr-xr-x+ 1 jet なし      0 Apr 16 01:30 Math
-rw-r--r--  1 jet なし   3084 Feb  6 20:46 NDBM_File.pm
-rw-r--r--  1 jet なし   4291 Feb  6 20:46 O.pm
-rw-r--r--  1 jet なし  16226 Feb  6 20:46 Opcode.pm
-rw-r--r--  1 jet なし  20347 Feb  6 20:46 POSIX.pm
-rw-r--r--  1 jet なし  80706 Feb  6 20:46 POSIX.pod
drwxr-xr-x+ 1 jet なし      0 Apr 16 01:30 PerlIO
-rw-r--r--  1 jet なし   3809 Feb  6 20:46 SDBM_File.pm
drwxr-xr-x+ 1 jet なし      0 Apr 16 01:30 Scalar
-rw-r--r--  1 jet なし  37062 Feb  6 20:46 Socket.pm
-rw-r--r--  1 jet なし  49924 Feb  6 20:46 Storable.pm
drwxr-xr-x+ 1 jet なし      0 Apr 16 01:30 Sub
drwxr-xr-x+ 1 jet なし      0 Apr 16 01:30 Sys
drwxr-xr-x+ 1 jet なし      0 Apr 16 01:30 Time
drwxr-xr-x+ 1 jet なし      0 Apr 16 01:30 Unicode
-rw-r--r--  1 jet なし  52505 Feb  6 20:46 Win32.pm
drwxr-xr-x+ 1 jet なし      0 Apr 16 01:30 Win32API
-rw-r--r--  1 jet なし   1305 Feb  6 20:46 Win32CORE.pm
-rw-r--r--  1 jet なし  16353 Feb  6 20:46 attributes.pm
drwxr-xr-x+ 1 jet なし      0 Apr 16 01:30 auto
-rw-r--r--  1 jet なし  22950 Feb  6 20:46 encoding.pm
-rw-r--r--  1 jet なし   6136 Feb  6 20:46 lib.pm
-rw-r--r--  1 jet なし   9892 Feb  6 20:46 mro.pm
-rw-r--r--  1 jet なし    997 Feb  6 20:46 ops.pm
-rw-r--r--  1 jet なし  25394 Feb  6 20:46 re.pm
drwxr-xr-x+ 1 jet なし      0 Apr 16 01:30 threads
-rw-r--r--  1 jet なし  37951 Feb  6 20:46 threads.pm
```

**Comment by masatake** [comment]
The diff of install files under the directory:
```
$ diff -uN <(sort /tmp/mypc)  <(sort /tmp/appveyor )
--- /proc/self/fd/11	2021-04-16 02:09:32.119607843 +0900
+++ /proc/self/fd/12	2021-04-16 02:09:32.119607843 +0900
@@ -1,55 +1,31 @@
 attributes.pm
 auto
-B
 B.pm
-Compress
-Config_git.pl
 Config_heavy.pl
 Config.pm
-Config.pod
-CORE
 Cwd.pm
 Data
-DB_File.pm
-Devel
 Digest
 DynaLoader.pm
 Encode
 Encode.pm
-encoding.pm
 Errno.pm
 Fcntl.pm
 File
-Filter
-GDBM_File.pm
-Hash
 I18N
 IO
 IO.pm
-IPC
 lib.pm
 List
-Math
 MIME
 mro.pm
-NDBM_File.pm
 Opcode.pm
-O.pm
-ops.pm
 PerlIO
 POSIX.pm
-POSIX.pod
 re.pm
 Scalar
-SDBM_File.pm
 Socket.pm
 Storable.pm
-Sub
-Sys
-threads
-threads.pm
 Time
-Unicode
 Win32API
-Win32CORE.pm
 Win32.pm
```

**Comment by masatake** [comment]
threads.pm is listed in https://cygwin.com/packages/x86_64/perl/perl-5.32.1-1.
It is not listed in https://cygwin.com/packages/x86_64/perl_base/perl_base-5.32.1-1.

I wonder this is a package bug of perl_base or not. I cannot find the history of the changes.

https://cygwin.com/packages/summary/automake1.16.html , this page says automaker requires perl_base, not perl.
Here is a gap.

I should report this to cygwin project (https://cygwin.com/problems.html).

**Comment by masatake** [comment]
I opened https://github.com/universal-ctags/ctags/pull/2957 .

This, #2953 should be merged after merging #2957.
