### PR TITLE
Fix C++ parser crash with unclosed angle brackets

### LINKED ISSUE #4361: Universal Ctags crashes when parsing unclosed C++ angle brackets
Universal-Ctags bug report 2026-01-02:

I am creating an issue from my email bug report at the request of `@masatake`.

Universal-ctags tries to access heap memory after it has been freed
somehow. *cxxParserParseClassStructOrUnionInternal()* calls
*cxxTokenChainDestroy()*, which calls *cxxTokenDestroy()*, which then
calls *cxxTokenChainDestroy()*. I think the global token chain is
being accessed during
*cxxParserParseTemplateAngleBracketsToSeparateChain()*. It doesn't
look like ParseClassStructOrUnionInternal returns between destroying
the token chain and assigning a new value to
`g_cxx.pTemplateSpecializationTokenChain`.

Found with AFL++ running overnight in Docker CE running in openSUSE on
Windows Subsystem for Linux running on a Windows 10 host.

The reason I decided to fuzz Universal-ctags was because it crashed
when I was running it on GCC's source code and I was curious about what
kind of inputs would make u-ctags crash.

Reproducible: happens every time with AddressSanitizer enabled. The
bug is not detected when running without AddressSanitizer
instrumentation.

Note: when debugging with gdb, I had to set the environment variable
ASAN_OPTIONS=abort_on_error=1 to get GDB to break in the right place.

Impact: crash (ASAN build), possible memory corruption (without ASAN)

All of these crashes are variations of crash id `#8`.

u-ctags version: p6.2.20251130.0-2-g6858451dc
Compiler: afl-clang-lto
Clang version: 19.1.7
GCC version: gcc (SUSE Linux) 15.1.1 20250714
Bash version: GNU bash, version 5.2.37(1)-release (x86_64-suse-linux)
AFL++ version: 4.35a
Configuration: (export CC=afl-clang-lto CXX=afl-clang-lto++ CFLAGS='-O3 -ffast-math -fno-finite-math-only -g -fno-omit-frame-pointer -mtune=skylake' AFL_USE_ASAN=1;time dash ./configure && time make -j6)
uname -a: `Linux MSI 6.6.87.2-microsoft-standard-WSL2 #1 SMP PREEMPT_DYNAMIC Thu Jun  5 18:30:46 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux`
Hardware: MSI GS63 Stealth 8RE

Host: Windows 10 22H2 (OS Build 19045.6691) x86_64-v3
WSL distro: openSUSE 16.0
Windows Terminal version: 1.23.13503.0
Docker CE version: 28.3.2-ce, build e77ff99ed
Docker image: custom build of aflplusplus Dockerfile, I think(?).

WSL version:
```
WSL version: 2.6.2.0
Kernel version: 6.6.87.2-1
WSLg version: 1.0.71
MSRDC version: 1.2.6353
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.19045.6691
```

To reproduce: Compile with -fsanitize=address,undefined and paste the
crashing input into a .cpp file and run universal-ctags on it.

**Crash `#8,9` heap-use-after-free**

Both simplify to the following: `class<><{[]{class<`

<details>

<summary> AddressSanitizer output and GDB backtrace </summary>

```
=================================================================
==955892==ERROR: AddressSanitizer: heap-use-after-free on address
0x7c2ff5b2c840 at pc 0x000000558dfa bp 0x7fffffffcdd0 sp
0x7fffffffcdc8
READ of size 8 at 0x7c2ff5b2c840 thread T0
    #0 0x000000558df9 in cxxTokenChainDestroy parsers/cxx/cxx_token_chain.c:43
    #1 0x00000050469a in cxxParserParseClassStructOrUnionInternal parsers/cxx/cxx_parser.c:1130
    #2 0x00000050469a in cxxParserParseClassStructOrUnion parsers/cxx/cxx_parser.c:1511
    #3 0x00000050c372 in cxxParserParseBlockInternal parsers/cxx/cxx_parser_block.c:431
    #4 0x00000050e708 in cxxParserParseBlockFull parsers/cxx/cxx_parser_block.c:893
    #5 0x00000050e708 in cxxParserParseBlock parsers/cxx/cxx_parser_block.c:904
    #6 0x000000521d53 in cxxParserHandleLambda parsers/cxx/cxx_parser_lambda.c:299
    #7 0x0000004ff8ca in cxxParserParseAndCondenseSubchainsUpToOneOf parsers/cxx/cxx_parser.c:248
    #8 0x00000052b45f in cxxParserParseTemplateAngleBracketsInternal parsers/cxx/cxx_parser_template.c:639
    #9 0x00000052ce20 in cxxParserParseTemplateAngleBrackets parsers/cxx/cxx_parser_template.c:670
    #10 0x00000052ce20 in cxxParserParseTemplateAngleBracketsToSeparateChain parsers/cxx/cxx_parser_template.c:708
    #11 0x0000005046a1 in cxxParserParseClassStructOrUnionInternal parsers/cxx/cxx_parser.c:1132
    #12 0x0000005046a1 in cxxParserParseClassStructOrUnion parsers/cxx/cxx_parser.c:1511
    #13 0x00000050c372 in cxxParserParseBlockInternal parsers/cxx/cxx_parser_block.c:431
    #14 0x00000050e708 in cxxParserParseBlockFull parsers/cxx/cxx_parser_block.c:893
    #15 0x00000050e708 in cxxParserParseBlock parsers/cxx/cxx_parser_block.c:904
    #16 0x0000004ff437 in cxxParserMain parsers/cxx/cxx_parser.c:2018
    #17 0x00000050849d in cxxCppParserMain parsers/cxx/cxx_parser.c:2077
    #18 0x000000445481 in createTagsForFile main/parse.c:4395
    #19 0x000000445481 in createTagsWithFallback1 main/parse.c:4521
    #20 0x000000445f7e in createTagsWithFallback main/parse.c:4612
    #21 0x000000445f7e in parseMio main/parse.c:4774
    #22 0x00000045ee13 in parseFileWithMio main/parse.c:4821
    #23 0x00000045f53b in parseFile main/parse.c:4757
    #24 0x00000041caff in createTagsForEntry main/main.c:221
    #25 0x00000041d1cf in createTagsForArgs main/main.c:266
    #26 0x00000041d1cf in batchMakeTags main/main.c:360
    #27 0x00000041da74 in runMainLoop main/main.c:332
    #28 0x00000041da74 in ctags_cli_main main/main.c:586
    #29 0x7ffff6c3033f in __libc_start_call_main (/lib64/libc.so.6+0x2a33f) (BuildId: 41d443e8a12973d20e705f4efb33ee3bed03f727)
    #30 0x7ffff6c30408 in __libc_start_main_alias_1 (/lib64/libc.so.6+0x2a408) (BuildId: 41d443e8a12973d20e705f4efb33ee3bed03f727)
    #31 0x00000041c534 in _start ../sysdeps/x86_64/start.S:115

0x7c2ff5b2c840 is located 0 bytes inside of 24-byte region
[0x7c2ff5b2c840,0x7c2ff5b2c858)
freed by thread T0 here:
    #0 0x7ffff792168b  (/lib64/libasan.so.8+0x12168b) (BuildId: 0ca023704e42220944eaf9284f2795a514ab2fed)
    #1 0x00000050469a in cxxParserParseClassStructOrUnionInternal parsers/cxx/cxx_parser.c:1130
    #2 0x00000050469a in cxxParserParseClassStructOrUnion parsers/cxx/cxx_parser.c:1511
    #3 0x00000050c372 in cxxParserParseBlockInternal parsers/cxx/cxx_parser_block.c:431
    #4 0x00000050e708 in cxxParserParseBlockFull parsers/cxx/cxx_parser_block.c:893
    #5 0x00000050e708 in cxxParserParseBlock parsers/cxx/cxx_parser_block.c:904
    #6 0x0000004ff437 in cxxParserMain parsers/cxx/cxx_parser.c:2018
    #7 0x00000050849d in cxxCppParserMain parsers/cxx/cxx_parser.c:2077
    #8 0x000000445481 in createTagsForFile main/parse.c:4395
    #9 0x000000445481 in createTagsWithFallback1 main/parse.c:4521
    #10 0x000000445f7e in createTagsWithFallback main/parse.c:4612
    #11 0x000000445f7e in parseMio main/parse.c:4774
    #12 0x00000045ee13 in parseFileWithMio main/parse.c:4821
    #13 0x00000045f53b in parseFile main/parse.c:4757
    #14 0x00000041caff in createTagsForEntry main/main.c:221
    #15 0x00000041d1cf in createTagsForArgs main/main.c:266
    #16 0x00000041d1cf in batchMakeTags main/main.c:360
    #17 0x00000041da74 in runMainLoop main/main.c:332
    #18 0x00000041da74 in ctags_cli_main main/main.c:586
    #19 0x7ffff6c3033f in __libc_start_call_main (/lib64/libc.so.6+0x2a33f) (BuildId: 41d443e8a12973d20e705f4efb33ee3bed03f727)

previously allocated by thread T0 here:
    #0 0x7ffff79229cb in malloc (/lib64/libasan.so.8+0x1229cb) (BuildId: 0ca023704e42220944eaf9284f2795a514ab2fed)
    #1 0x000000b66ee0 in eMalloc main/routines.c:220
    #2 0x000000558be1 in cxxTokenChainCreate parsers/cxx/cxx_token_chain.c:30
    #3 0x00000052cdbe in cxxParserParseTemplateAngleBracketsToSeparateChain parsers/cxx/cxx_parser_template.c:702
    #4 0x0000005046a1 in cxxParserParseClassStructOrUnionInternal parsers/cxx/cxx_parser.c:1132
    #5 0x0000005046a1 in cxxParserParseClassStructOrUnion parsers/cxx/cxx_parser.c:1511
    #6 0x00000050c372 in cxxParserParseBlockInternal parsers/cxx/cxx_parser_block.c:431
    #7 0x00000050e708 in cxxParserParseBlockFull parsers/cxx/cxx_parser_block.c:893
    #8 0x00000050e708 in cxxParserParseBlock parsers/cxx/cxx_parser_block.c:904
    #9 0x0000004ff437 in cxxParserMain parsers/cxx/cxx_parser.c:2018
    #10 0x00000050849d in cxxCppParserMain parsers/cxx/cxx_parser.c:2077
    #11 0x000000445481 in createTagsForFile main/parse.c:4395
    #12 0x000000445481 in createTagsWithFallback1 main/parse.c:4521
    #13 0x000000445f7e in createTagsWithFallback main/parse.c:4612
    #14 0x000000445f7e in parseMio main/parse.c:4774
    #15 0x00000045ee13 in parseFileWithMio main/parse.c:4821
    #16 0x00000045f53b in parseFile main/parse.c:4757
    #17 0x00000041caff in createTagsForEntry main/main.c:221
    #18 0x00000041d1cf in createTagsForArgs main/main.c:266
    #19 0x00000041d1cf in batchMakeTags main/main.c:360
    #20 0x00000041da74 in runMainLoop main/main.c:332
    #21 0x00000041da74 in ctags_cli_main main/main.c:586
    #22 0x7ffff6c3033f in __libc_start_call_main (/lib64/libc.so.6+0x2a33f) (BuildId: 41d443e8a12973d20e705f4efb33ee3bed03f727)

SUMMARY: AddressSanitizer: heap-use-after-free
parsers/cxx/cxx_token_chain.c:43 in cxxTokenChainDestroy
Shadow bytes around the buggy address:
  0x7c2ff5b2c580: fd fd fa fa fd fd fd fa fa fa fd fd fd fd fa fa
  0x7c2ff5b2c600: 00 00 00 00 fa fa 00 00 00 fa fa fa 00 00 00 00
  0x7c2ff5b2c680: fa fa 00 00 00 fa fa fa 00 00 00 00 fa fa 00 00
  0x7c2ff5b2c700: 00 fa fa fa 00 00 00 00 fa fa 00 00 00 fa fa fa
  0x7c2ff5b2c780: fd fd fd fd fa fa 00 00 00 fa fa fa fd fd fd fa
=>0x7c2ff5b2c800: fa fa fd fd fd fd fa fa[fd]fd fd fa fa fa fd fd
  0x7c2ff5b2c880: fd fa fa fa fd fd fd fd fa fa 00 00 00 fa fa fa
  0x7c2ff5b2c900: 00 00 00 00 fa fa 00 00 00 fa fa fa 00 00 00 fa
  0x7c2ff5b2c980: fa fa 00 00 00 00 fa fa 00 00 00 fa fa fa 00 00
  0x7c2ff5b2ca00: 00 00 fa fa 00 00 00 fa fa fa 00 00 00 fa fa fa
  0x7c2ff5b2ca80: 00 00 00 00 fa fa 00 00 00 fa fa fa 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==955892==ABORTING

Program received signal SIGABRT, Aborted.
0x00007ffff6c9a45c in __pthread_kill_implementation () from /lib64/libc.so.6
Missing separate debuginfos, use: zypper install
glibc-debuginfo-2.40-160000.2.2.x86_64
libasan8-debuginfo-15.1.1+git9973-160000.2.2.x86_64
libxml2-2-debuginfo-2.13.8-160000.2.2.x86_64
libyaml-0-2-debuginfo-0.2.5-160000.3.2.x86_64
libpcre2-8-0-debuginfo-10.45-160000.2.2.x86_64
libubsan1-debuginfo-15.1.1+git9973-160000.2.2.x86_64
libstdc++6-debuginfo-15.1.1+git9973-160000.2.2.x86_64
gcc15-debuginfo-15.1.1+git9973-160000.2.2.x86_64
libz1-debuginfo-1.2.13-160000.2.2.x86_64
liblzma5-debuginfo-5.8.1-160000.2.2.x86_64
(gdb) bt
#0  0x00007ffff6c9a45c in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007ffff6c46fc6 in raise () from /lib64/libc.so.6
#2  0x00007ffff6c2e917 in abort () from /lib64/libc.so.6
#3  0x00007ffff7944d5f in ?? () from /lib64/libasan.so.8
#4  0x00007ffff7955a4c in ?? () from /lib64/libasan.so.8
#5  0x00007ffff792e5b1 in ?? () from /lib64/libasan.so.8
#6  0x00007ffff792db01 in ?? () from /lib64/libasan.so.8
#7  0x00007ffff792ee2c in __asan_report_load8 () from /lib64/libasan.so.8
#8  0x0000000000558dfa in cxxTokenChainDestroy (tc=0x7c2ff5b2c840)
    at parsers/cxx/cxx_token_chain.c:43
#9  0x000000000050469b in cxxParserParseClassStructOrUnionInternal (eKeyword=CXXKeywordCLASS,
    uTagKind=16, uScopeType=2) at parsers/cxx/cxx_parser.c:1130
#10 cxxParserParseClassStructOrUnion (eKeyword=eKeyword@entry=CXXKeywordCLASS,
    uTagKind=uTagKind@entry=16, uScopeType=uScopeType@entry=2) at parsers/cxx/cxx_parser.c:1511
#11 0x000000000050c373 in cxxParserParseBlockInternal (
    bExpectClosingBracket=bExpectClosingBracket@entry=true, bExported=bExported@entry=false)
    at parsers/cxx/cxx_parser_block.c:431
#12 0x000000000050e709 in cxxParserParseBlockFull (bExpectClosingBracket=true, bExported=false)
    at parsers/cxx/cxx_parser_block.c:893
#13 cxxParserParseBlock (bExpectClosingBracket=bExpectClosingBracket@entry=true)
    at parsers/cxx/cxx_parser_block.c:904
#14 0x0000000000521d54 in cxxParserHandleLambda (pParenthesis=<optimized out>)
    at parsers/cxx/cxx_parser_lambda.c:299
#15 0x00000000004ff8cb in cxxParserParseAndCondenseSubchainsUpToOneOf (
    uTokenTypes=uTokenTypes@entry=8388609,
    uInitialSubchainMarkerTypes=uInitialSubchainMarkerTypes@entry=3670016,
    bCanReduceInnerElements=bCanReduceInnerElements@entry=false) at parsers/cxx/cxx_parser.c:248
#16 0x000000000050203e in cxxParserParseUpToOneOf (uTokenTypes=uTokenTypes@entry=8388609,
    bCanReduceInnerElements=bCanReduceInnerElements@entry=false) at parsers/cxx/cxx_parser.c:339
#17 0x000000000052b460 in cxxParserParseTemplateAngleBracketsInternal (
    bCaptureTypeParameters=bCaptureTypeParameters@entry=false,
    iNestedTemplateLevel=iNestedTemplateLevel@entry=0) at parsers/cxx/cxx_parser_template.c:639
#18 0x000000000052ce21 in cxxParserParseTemplateAngleBrackets (bCaptureTypeParameters=false)
    at parsers/cxx/cxx_parser_template.c:670
#19 cxxParserParseTemplateAngleBracketsToSeparateChain (
    bCaptureTypeParameters=bCaptureTypeParameters@entry=false)
    at parsers/cxx/cxx_parser_template.c:708
#20 0x00000000005046a2 in cxxParserParseClassStructOrUnionInternal (eKeyword=CXXKeywordCLASS,
    uTagKind=16, uScopeType=2) at parsers/cxx/cxx_parser.c:1132
#21 cxxParserParseClassStructOrUnion (eKeyword=eKeyword@entry=CXXKeywordCLASS,
    uTagKind=uTagKind@entry=16, uScopeType=uScopeType@entry=2) at parsers/cxx/cxx_parser.c:1511
#22 0x000000000050c373 in cxxParserParseBlockInternal (
    bExpectClosingBracket=bExpectClosingBracket@entry=false, bExported=bExported@entry=false)
    at parsers/cxx/cxx_parser_block.c:431
#23 0x000000000050e709 in cxxParserParseBlockFull (bExpectClosingBracket=false, bExported=false)
    at parsers/cxx/cxx_parser_block.c:893
#24 cxxParserParseBlock (bExpectClosingBracket=bExpectClosingBracket@entry=false)
    at parsers/cxx/cxx_parser_block.c:904
#25 0x00000000004ff438 in cxxParserMain (passCount=passCount@entry=1)
    at parsers/cxx/cxx_parser.c:2018
--Type <RET> for more, q to quit, c to continue without paging--c
#26 0x000000000050849e in cxxCppParserMain (passCount=1) at parsers/cxx/cxx_parser.c:2077
#27 0x0000000000445482 in createTagsForFile (language=-173136832, passCount=1) at main/parse.c:4395
#28 createTagsWithFallback1 (language=language@entry=23,
    exclusive_subparser=exclusive_subparser@entry=0x7bfff48fabc0) at main/parse.c:4521
#29 0x0000000000445f7f in createTagsWithFallback (fileName=0x7c2ff5ae0250 "crash_8-2026-01-02.cpp",
    language=23, mio=<optimized out>, mtime=<optimized out>, failureInOpenning=0x7bfff48fabb0)
    at main/parse.c:4612
#30 parseMio (fileName=fileName@entry=0x7c2ff5ae0250 "crash_8-2026-01-02.cpp",
    language=language@entry=23, mio=<optimized out>, mtime=<optimized out>,
    useSourceFileTagPath=useSourceFileTagPath@entry=true, clientData=clientData@entry=0x0)
    at main/parse.c:4774
#31 0x000000000045ee14 in parseFileWithMio (
    fileName=fileName@entry=0x7c2ff5ae0250 "crash_8-2026-01-02.cpp", mio=mio@entry=0x0,
    clientData=clientData@entry=0x0) at main/parse.c:4821
#32 0x000000000045f53c in parseFile (fileName=fileName@entry=0x7c2ff5ae0250 "crash_8-2026-01-02.cpp")
    at main/parse.c:4757
#33 0x000000000041cb00 in createTagsForEntry (entryName=0x7c2ff5ae0250 "crash_8-2026-01-02.cpp")
    at main/main.c:221
#34 0x000000000041d1d0 in createTagsForArgs (args=0x7c3ff5ae0010) at main/main.c:266
#35 batchMakeTags (args=0x7c3ff5ae0010, user=<optimized out>) at main/main.c:360
#36 0x000000000041da75 in runMainLoop (args=0x7c3ff5ae0010) at main/main.c:332
#37 ctags_cli_main (argc=<optimized out>, argv=0x7fffffffdb40) at
main/main.c:586
#38 0x00007ffff6c30340 in __libc_start_call_main () from /lib64/libc.so.6
#39 0x00007ffff6c30409 in __libc_start_main_impl () from /lib64/libc.so.6
#40 0x000000000041c535 in _start () at ../sysdeps/x86_64/start.S:115
(gdb)
```

</details>

**Crash `#50`**
Simplifies to `class<><[](){[](){class<`

**Crash `#165, 187,195`**
Similar to id:8 or id:9 but with some parentheses: `class<><{[](){class<`

**Crash `#169`**
Nearly identical to crash `#8`. `class<;<{[]{class<`

**Crash `#170`**
`{class<[[]{class<`

Patch to fix crash `#8`.
*cxxParserParseTemplatingAngleBracketsToSeparateChain()* seemed to be
referencing `pTemplateSpecializationTokenChain` somewhere, but setting
that variable to `NULL` immediately after being freed fixed the crash.

```patch
diff --git a/parsers/cxx/cxx_parser.c b/parsers/cxx/cxx_parser.c
index 393ef2e86..52a186598 100644
--- a/parsers/cxx/cxx_parser.c
+++ b/parsers/cxx/cxx_parser.c
@@ -1128,6 +1128,7 @@ static bool cxxParserParseClassStructOrUnionInternal(

                if(g_cxx.pTemplateSpecializationTokenChain)

cxxTokenChainDestroy(g_cxx.pTemplateSpecializationTokenChain);
+               g_cxx.pTemplateSpecializationTokenChain = NULL;

                g_cxx.pTemplateSpecializationTokenChain =
cxxParserParseTemplateAngleBracketsToSeparateChain(false);
                if(!g_cxx.pTemplateSpecializationTokenChain)
```

### PR DESCRIPTION
**Pull request by Quipyowert2**
Fixes #4361.

I think the problem was that *cxxParserParseTemplateAngleBracketsToSeparateChain()*, or one of the functions it calls, was referencing `pTemplateSpecializationTokenChain` after it had been freed but before it had been set to a valid value.

I added a unit test to check that the invalid C++ code snippet does not crash the C++ parser.

### CODE REVIEW

**Review by masatake — CHANGES_REQUESTED** [review]
Thank you for making a pull request.
Could add a file, README to Units/parser-cxx.r/unclosed-angle-bracket.d with the following contents?
```
This is a crash test.
```

**Comment by masatake** [comment]
```
  ##valgrind-error:                       1
	parser-cxx.r/unclosed-angle-bracket
	............................................................
	==11297== Memcheck, a memory error detector
	==11297== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
	==11297== Using Valgrind-3.22.0 and LibVEX; rerun with -h for copyright info
	==11297== Command: ./ctags --verbose --options=NONE --fields=-T --optlib-dir=+./Units/parser-cxx.r/unclosed-angle-bracket.d/optlib -o - ./Units/parser-cxx.r/unclosed-angle-bracket.d/input.cxx
	==11297== Parent PID: 7788
	==11297== 
	==11297== 
	==11297== HEAP SUMMARY:
	==11297==     in use at exit: 21,924 bytes in 760 blocks
	==11297==   total heap usage: 13,440 allocs, 12,680 frees, 691,139 bytes allocated
	==11297== 
	==11297== 688 (48 direct, 640 indirect) bytes in 2 blocks are definitely lost in loss record 563 of 565
	==11297==    at 0x4846828: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
	==11297==    by 0x2DDEB6: eMalloc (routines.c:220)
	==11297==    by 0x190FD5: cxxTokenChainCreate (cxx_token_chain.c:30)
	==11297==    by 0x187A04: cxxParserParseTemplateAngleBracketsToSeparateChain (cxx_parser_template.c:702)
	==11297==    by 0x17C9E3: cxxParserParseClassStructOrUnionInternal (cxx_parser.c:1133)
	==11297==    by 0x17D42F: cxxParserParseClassStructOrUnion (cxx_parser.c:1512)
	==11297==    by 0x17F09F: cxxParserParseBlockInternal (cxx_parser_block.c:431)
	==11297==    by 0x17FBF9: cxxParserParseBlockFull (cxx_parser_block.c:893)
	==11297==    by 0x17FC3C: cxxParserParseBlock (cxx_parser_block.c:904)
	==11297==    by 0x184EFF: cxxParserHandleLambda (cxx_parser_lambda.c:299)
	==11297==    by 0x17B263: cxxParserParseAndCondenseSubchainsUpToOneOf (cxx_parser.c:248)
	==11297==    by 0x17B477: cxxParserParseUpToOneOf (cxx_parser.c:339)
	==11297== 
	==11297== LEAK SUMMARY:
	==11297==    definitely lost: 48 bytes in 2 blocks
	==11297==    indirectly lost: 640 bytes in 12 blocks
	==11297==      possibly lost: 0 bytes in 0 blocks
	==11297==    still reachable: 21,236 bytes in 746 blocks
	==11297==         suppressed: 0 bytes in 0 blocks
	==11297== Reachable blocks (those to which a pointer was found) are not shown.
	==11297== To see them, rerun with: --leak-check=full --show-leak-kinds=all
	==11297== 
	==11297== For lists of detected and suppressed errors, rerun with: -s
	==11297== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

**Comment by masatake** [comment]
One more.

See pTemplateSpecializationTokenChain to NULL f(g_cxx.pTemplateSpecializationTokenChain).

```
diff --git a/parsers/cxx/cxx_parser.c b/parsers/cxx/cxx_parser.c
index 393ef2e86..d153b9e90 100644
--- a/parsers/cxx/cxx_parser.c
+++ b/parsers/cxx/cxx_parser.c
@@ -1127,7 +1127,10 @@ static bool cxxParserParseClassStructOrUnionInternal(
        // }
 
        if(g_cxx.pTemplateSpecializationTokenChain)
+       {
            cxxTokenChainDestroy(g_cxx.pTemplateSpecializationTokenChain);
+           g_cxx.pTemplateSpecializationTokenChain = NULL;
+       }
 
        g_cxx.pTemplateSpecializationTokenChain = cxxParserParseTemplateAngleBracketsToSeparateChain(false);
        if(!g_cxx.pTemplateSpecializationTokenChain)
```

Could you update your pull request?

**Comment by Quipyowert2** [comment]
I added the same change to cxxParseNewStatementFull, this seems to fix the leak. The original code does not destroy the template specialization chain, because assumes `cxxParserParseTemplateAngleBracketsToTemplateChain()` is called at some point. When running ctags on crash `#8` from issue #4361, the function is never called, so there is a memory leak. Should be fixed now.

File: parsers/cxx/cxx_parser.c [hunk 1]
```diff
@@ -57,6 +57,13 @@ void cxxParserNewStatementFull(bool bExported)
 		// we don't care about stale specializations as they
 		// are destroyed wen the base template prefix is extracted
 	}
+	// Fixed a memory leak by freeing the specializations here anyway.
+	// For certain invalid inputs, parseTemplateAngleBracketsToTemplateChain is never called.
+	if(g_cxx.pTemplateSpecializationTokenChain)
+	{
+		cxxTokenChainDestroy(g_cxx.pTemplateSpecializationTokenChain);
+		g_cxx.pTemplateSpecializationTokenChain = NULL;
+	}
```
Comment (masatake) [inline parsers/cxx/cxx_parser.c:66]: Thank you. But could you split the commit into two?
The original commit is for fixing a crash. The second one is for fixing the memory leak.
I happy if you add a test case for the second one, reproducing a memory leak.

Comment (masatake) [reply parsers/cxx/cxx_parser.c:66]: Do you have any input file causing the memory leak?

Comment (Quipyowert2) [reply parsers/cxx/cxx_parser.c:66]: Crash `#8` from #4361 causes the memory leak.

How do I add a Valgrind test that checks that there are no leaks in the code I changed?

Comment (masatake) [reply parsers/cxx/cxx_parser.c:66]: Thank you. Reproduced.

```
[yamato@dev64]~/var/ctags-github% make units VG=1 UNITS=parser-cxx.r/unclosed-angle-bracket
...
Summary (see CMDLINE.tmp to reproduce without test harness)
------------------------------------------------------------
  #passed:                                0
  #FIXED:                                 0
  #FAILED (broken args.ctags?):           0
  #FAILED (unexpected-exit-status):       0
  #FAILED (unexpected-output):            0
  #TIMED-OUT (10s):                       0
  #skipped (features):                    0
  #skipped (languages):                   0
  #known-bugs:                            0
  #valgrind-error:                        1
	parser-cxx.r/unclosed-angle-bracket
make: *** [Makefile:8208: units] Error 1
[yamato@dev64]~/var/ctags-github% less Units/parser-cxx.r/unclosed-angle-bracket.d/VALGRIND.tmp 
...
```

Now I understand you don't have to add anything to your pull request.
The test case added in the first commit demonstrates the memory leak that is fixed in the second commit. I was wrong. The two commits should be one; I will squash into one when merging.
