### PR TITLE
Misc man page fixes

### LINKED ISSUE #1082: Incompatible behavior: "typeref" field of C
### Source`test.c`

``` c
static int f(int x) { return 42; }
static bool wakeup_spi = false;
```
### Universal Ctags result

``` tags
f   test.c  /^static int f(int x) { return 42; }$/;"    f   typeref:typename:int    file:
wakeup_spi  /tmp/test-spi.c /^  static bool wakeup_spi = false;$/;" v   typeref:typename:bool   file:
```
#### Version

```
Universal Ctags 0.0.0(c984455), Copyright (C) 2015 Universal Ctags Team
```
### Exuberant Ctags result

``` tags
f   test.c  /^static int f(int x) { return 42; }$/;"    f   file:
wakeup_spi  /tmp/test-spi.c /^  static bool wakeup_spi = false;$/;" v   file:
```
## Expected behavior

According to man page of Universal Ctags and Exuberant Ctags:

> t   Type and name of a variable or typedef as "typeref:" field [enabled]

It seems that both the two forks don't conform to man page:
-  Exuberant Ctags only prints this field for definition of variable of struct type
-  Universal Ctags even prints it for functions

### PR DESCRIPTION
**Pull request by masatake**
Close #1082.

### CODE REVIEW

File: main/options.c [hunk 1]
```diff
@@ -248,12 +248,12 @@ static optionDescription LongOptionDescription [] = {
  {1,"      Include extra tag entries for selected information (flags: \"Ffq.\") [F]."},
  {1,"  --extras-<LANG|*>=[+|-]flags"},
  {1,"      Include <LANG> own extra tag entries for selected information"},
- {1,"      (flags: --list-extras=<LANG>)."},
+ {1,"      (flags: inquire the output of --list-extras=<LANG> option)."},
```
Comment (codebrainz) [inline main/options.c]: If I understand correctly[0], I think it would sound more natural to replace "inquire" with "see" or "refer to". Same with below on L256.

[0]: That it means: to see what you can use for the `flags`, use `--list-extras` and it will print them for you.

Comment (masatake) [reply main/options.c]: Thank you!

**Comment by masatake** [comment]
Refected the comment from @codebrainz, and updated the commit.
