### PR TITLE
SML: avoid accessing `enabled' field of wrong type

### LINKED ISSUE #528: Assertion failed on parsing malformed SML file (main/parse.c:1372)
How to reproduce:
```
$ echo and > and.sml
$ ctags and.sml
ctags: main/parse.c:1372: boolean isLanguageKindEnabled(const langType, char): Assertion `kindOpt' failed.
ctags: main/parse.c:1372: parsing and.sml:1 as SML
Aborted
```

this issue is found by afl-fuzz

### PR DESCRIPTION
**Pull request by masatake**
This is reported and suggested by @kcwu.

Quoted from the report from @kcwu (#528):

    I found I can reproduce it with clang but not with gcc. The problem is

     72| static void makeSmlTag (smlKind type, vString *name)
     73| {
     74|         tagEntryInfo tag;
     75|
     76|         if (! SmlKinds [type].enabled)
     77|                 return;

    where type = K_NONE = -1.
    It's out of bound access for SmlKinds[-1] and thus depends on memory layout.

Close #528.

Signed-off-by: Masatake YAMATO <yamato@redhat.com>

### CODE REVIEW

File: parsers/sml.c [hunk 1]
```diff
@@ -31,7 +32,8 @@ typedef enum {
 	K_SIGNATURE,
 	K_STRUCTURE,
 	K_TYPE,
-	K_VAL
+	K_VAL,
+	K_LAST_ELT = K_VAL
```
Comment (b4n) [inline parsers/sml.c]: I'd use something like `K_COUNT /* must be last */` and simply keep it last, to avoid having to update it when adding a kind.  But that's mostly style, so it's your call.

**Comment by b4n** [comment]
LGTM

**Comment by masatake** [comment]
@b4n, thank you for reviewing. I updated as you suggested.

**Comment by b4n** [comment]
last commit LGTM, but apparently 3 more commits invited themselves here, yet they don't seem related ^^

**Comment by masatake** [comment]
Oh, I'm sorry. Pushed again.

**Comment by b4n** [comment]
LGTM now :)

**Comment by masatake** [comment]
@b4n, thank you for taking time.
