### PR TITLE
jscript: Support HTML comments

### LINKED ISSUE #4373: JavaScript in HTML: fails to parse after an HTML commen since JSX support
Parser: HTML or JS? I'm not sure at which level this should be fixed.
CTags version: master (b11e39a7a89dc0b556e843db5aa34d0198066b9d)

If JS embedded in HTML starts with `<!--`, the next symbol won't be properly recognized.  For example:

```console
$ cat /tmp/a.html
<!DOCTYPE html>
<head>
<script type="text/javascript">
<!--
function message() { alert( "Hello."); }
//-->
</script>
</head>
</html>
$ ./ctags -o- --extras=+g  /tmp/a.html
$ sed 's,^<!--,//&,' < /tmp/a.html > /tmp/b.html
$ cat /tmp/b.html
<!DOCTYPE html>
<head>
<script type="text/javascript">
//<!--
function message() { alert( "Hello."); }
//-->
</script>
</head>
</html>
$ ./ctags -o- --extras=+g  /tmp/b.html
message	/tmp/b.html	/^function message() { alert( "Hello."); }$/;"	f
```

This used to work before the JSX support (6c6799a20afaf844d64e628b029d3ee47113ad72).

I'm not quite sure whether the first (non-working) example works in a web browser because ECMAScript supports this special case, or if it's the browser doing this (so whether it should be on the JS or HTML side), but they seem to be happy with it, so we probably should be as well.  This breaks Geany's [simple.html](https://github.com/geany/geany/blob/master/tests/ctags/simple.html) test case (although it supposedly came from here, I couldn't find it in the history).

### PR DESCRIPTION
**Pull request by b4n**
This is a legacy feature for web browsers, but it still found in HTML-embedded JS in the wild.

This used not to be a problem until JSX support was introduced, which then handles these erroneously as regular HTML comments spanning all the way to the closing part.

See https://tc39.es/ecma262/multipage/additional-ecmascript-features-for-web-browsers.html#sec-html-like-comments and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Deprecated_and_obsolete_features#html_comments for the references.

Fixes #4373.

### CODE REVIEW

File: parsers/jscript.c [hunk 1]
```diff
@@ -1237,7 +1257,28 @@ static void readTokenFullRaw (tokenInfo *const token, bool include_newlines, vSt
...
+			if (d == '!')
+			{
+				d = getcFromInputFile ();
+				if (d != '-')
+					ungetcToInputFile (d);
+				else
+				{
+					d = getcFromInputFile ();
+					if (d != '-')
+						ungetcToInputFile (d);
```
Comment (jafl) [inline parsers/jscript.c:1275]: Should this also `ungetcToInputFile('-')`, since it has read `<!-` followed by something other than a dash?

File: parsers/jscript.c [hunk 2]
```diff
@@ -1322,11 +1360,7 @@ static void readTokenFullRaw (tokenInfo *const token, bool include_newlines, vSt
 				}
 				else if (d == '/')	/* is this the start of a comment?  */
 				{
-					skipToCharacterInInputFile ('\n');
-					/* if we care about newlines, put it back so it is seen */
-					if (include_newlines)
-						ungetcToInputFile ('\n');
-					goto getNextChar;
+					SKIP_COMMENT_SINGLE_AND_RETRY();
```
Comment (jafl) [inline parsers/jscript.c:1368]: The macro `SKIP_COMMENT_SINGLE_AND_RETRY` doesn't check the `include_newlines` flag, so the behavior is not identical.

Comment (b4n) [reply parsers/jscript.c:1368]: It is not, but that's on purpose: now it sets `newline_encountered` directly.
The only change this could actually results in is the representation (in `repr`) of the single-line comment **in case `include_newline` is `true`**.  AFAICT, this results in no practical change as it's only relevant inside parameter lists, but those don't set `include_newline` anyway, so we don't see any change in behavior.

We could keep putting back the `\n` as it was before, but this seems unnecessary if setting `newline_encountered` directly.

File: parsers/jscript.c (hunk 1 above)
Comment (b4n) [reply parsers/jscript.c:1275]: You are right, and the `!` as well.  Will fix -- although I doubt it'll result in actual problems, it still might bite us in the future.

Comment (b4n) [reply parsers/jscript.c:1275]: Should be fixed now

**Comment by b4n** [comment]
Interestingly, this very slightly changes behavior of valid code, because supporting this part of the standard has a possibly unexpected effect on valid code: imaging the following:

```javascript
let a = 42;
let b = 42<!--a;
```

Although pathological, this is valid JS with or without the HTML comment support, but the meaning is different:
* With HTML comment support, `b` is `42` (because it reads as `b = 42//a`)
* Without it, `b` is `false` (because it then reads as `b = 42 < (! (--a))`)

Hopefully nobody has written *any* of this in real life, but supporting this, even as per the standard, leads to change in behavior.  Note that both Firefox and Chromium behaves like this as they support this part of the standard, and so e.g. adding a space after `<` changes the meaning of the expression as mentioned above.

Just an interesting thought :slightly_smiling_face: -- and this feature is kind of silly altogether, although understandable in another era.

**Comment by b4n** [comment]
@jafl thanks for the review!
